[package]
name = "koko"
version = "0.2.0"
edition = "2024"

[dependencies]
kokoros = { path = "../kokoros" }

atty = "0.2"
clap = { version = "4.5.39", features = ["derive"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
