name: Build Release Binary

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build release binary
        run: |
          cargo build --release --bin koko

      - name: Save binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: koko-binary
          path: target/release/koko
          if-no-files-found: error